### ISSUE TITLE
Uncaught Error: watch $ATOM_HOME/packages ENOSPC

### ISSUE THREAD

**Issue by prithvinambiar** [atom-haskell/ide-haskell-hasktags#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [ide-haskell-hasktags](https://github.com/atom-haskell/ide-haskell-hasktags) package 0.0.12

### Stack Trace

Uncaught Error: watch /home/prithvi/.atom/packages ENOSPC

```
At events.js:160

Error: watch /home/prithvi/.atom/packages ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/ide-haskell-hasktags/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:43.2.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:39.9.0 core:backspace (input.hidden-input)
     -0:38.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:35.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-haskell 0.4.0 
autocomplete-haskell 1.0.1 
busy-signal 1.4.3 
haskell-ghc-mod 2.1.3 
haskell-pointfree 0.2.0 
haskell-scry 1.0.7 
hasklig 0.4.0 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.4 
ide-haskell-hasktags 0.0.12 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.7.4 
intentions 1.1.5 
language-haskell 1.14.3 
language-haskell-scoped 0.1.0 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by lierdakil** [comment]
It seems you're running into inotify watcher limit. Also seems like you're opening something in `$HOME` directly.

Usually, it is advisable to avoid opening files in `$HOME`, because there's a lot of files there and both Atom and ide-haskell-hasktags will try to register inotify watchers on each and every one of those. It's slow, and there's a system-wide limit on the possible number of inotify watchers.

See also http://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#troubleshooting for instructions on raising the limit (under 'Type Error: Unable to watch path')

**Comment by prithvinambiar** [comment]
Thanks @lierdakil for quick help.

I am closing this issue.
